### PR TITLE
handle CXCursor_VisibilityAttr, CXCursor_DLLImport and CXCursor_DLLExport in VisitMember

### PR DESCRIPTION
**Pull request by srxqds**
fixed: https://github.com/xoofx/CppAst.NET/issues/41

### CODE REVIEW

**Comment by xoofx** [comment]
Could you add a test that check this is working as expected?

**Comment by srxqds** [comment]
ok，i  will add tomrrow

**Comment by srxqds** [comment]
hi, @xoofx  you can help met to review it.
thank you.

**Comment by xoofx** [comment]
All good, thanks!

**Pull request merged**
